// Mocks generated by Mockito 5.4.0 from annotations
// in backup/test/music_collector_api.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;

import 'music_collector_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TestFunctions].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestFunctions extends _i1.Mock implements _i2.TestFunctions {
  @override
  void onPayErrorMessage(String? message) => super.noSuchMethod(
        Invocation.method(
          #onPayErrorMessage,
          [message],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onPayException(Exception? e) => super.noSuchMethod(
        Invocation.method(
          #onPayException,
          [e],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onPayCancel(bool? fromUser) => super.noSuchMethod(
        Invocation.method(
          #onPayCancel,
          [fromUser],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onComplete() => super.noSuchMethod(
        Invocation.method(
          #onComplete,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
