name: download translations from crowdin
# Controls when the workflow will run
on:
  schedule:
    - cron: 35 2,4,6,8,10 * * MON-FRI

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  download-translations:
    runs-on:  [self-hosted, macOS]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Run crowdin action
        uses: olachat/fe-crowdin-action@main
        with:
          action: 'download'
          pat_for_workflow:  ${{ secrets.PAT_FOR_WORKFLOW }}
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          branch: ${{ github.event.ref }}
          relative_path: '.'
          head_ref: ${{ github.head_ref }}
       
